version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: my_postgres_db_container
    environment:
      POSTGRES_USER: bobby
      POSTGRES_PASSWORD: bobby
      POSTGRES_DB: crud
    ports:
      - "5435:5432"
    volumes:
      - pgdata_volume:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata_volume: